{"name": "test_failure", "status": "failed", "statusDetails": {"message": "AssertionError: assert False", "trace": "def test_failure():\n        \"\"\"this test fails\"\"\"\n>       assert False\nE       assert False\n\ntest_sample.py:10: AssertionError"}, "description": "this test fails", "start": 1565021414657, "stop": 1565021414657, "uuid": "10f6b3d7-32bf-4933-91bd-8028fccf40b1", "historyId": "0c3a013bc8e6a218086a774ff101f3d3", "fullName": "test_sample#test_failure", "labels": [{"name": "parentSuite"}, {"name": "suite", "value": "test_sample"}, {"name": "subSuite"}, {"name": "host", "value": "PRO-IND-283"}, {"name": "thread", "value": "12440-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "test_sample"}]}